# Generated by Django 3.0.3 on 2020-02-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'shop',
            },
        ),
    ]
